"""
Django settings for treasurehunt project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&zasoan5!anv0o90(l1i(_3zqoc!--*l@uzh2(%cm*v@uax4#z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hunt.apps.HuntConfig',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'treasurehunt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'treasurehunt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_ROOT = 'C:\\Users\\Hemand\\PycharmProjects\\treasurehunt\\static\\hunt\\images'

MEDIA_URL = '/images/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

# https://graph.facebook.com/v2.8/oauth/access_token?client_id=1901884306696195&redirect_uri=http://localhost/&client_secret=1dff38165883b52d86c87a332989df58&code=AQDm4CH_2GoTAMK3XBVeplMm1Qu4Zjb6WtQhD8wBeZKT-40Uw4YeAC_6_7-iQ_Ny-7hjUCw0_WdiwNzao9san7y2vFuQzTFBdFA4Cdzea3HJ6Lzhct_jvfeWTX5wgrY24jAtMXVlXpmnqExOJYsiGB0tiFUfQo6Uzh5SIOXieYGq5FD8OH3X0bMrGikovrmfooLZ5bZvIAIJHvVV3ffM2nd1mtn7tSGkhO-uyG0JCgMvm6IhQZgbu8BxuDFXN2-8wPwYjcfvYSgj12pRYW2g6AVPWBpbrd1xq9FVcVzJW-LPabKgZX5mY8UWf77TK3QOAiUamwrGbf8kip4fgHF1dvi_#_=_

# https://www.facebook.com/v2.8/dialog/oauth?client_id=1901884306696195&redirect_uri=http://localhost/login/

#token = EAAbBwPKBKAMBAOq7LYzPVp49ofq1n3Wnyrii3ZAbyJOTMgZAtuL1EzaGKOS27hklQ44IivLsm7CnZCjugmqG18ZA4IsxdU9Q95LyqpZASDbVvOi0wF5BK74ssQ16BW249eB2KvYl2suWFxFcSgDyn6hahLEtLtiOZBp9pihLvkjgZDZD


 #"https://graph.facebook.com/v2.8/me?fields=id,name&access_token=
