# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('phone', models.IntegerField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
