# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='reg_status',
            field=models.BooleanField(default=False),
        ),
    ]
