# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_usermodel_reg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='reg_status',
        ),
    ]
