# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_usermodel_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
    ]
