# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0005_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.IntegerField()),
                ('question_text', models.CharField(max_length=1000)),
                ('question_image', models.FileField(upload_to='hunt/images/')),
                ('answer', models.CharField(max_length=100)),
                ('placeholder_ans', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
