# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0006_auto_20170408_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='level_no',
            field=models.IntegerField(unique=True),
        ),
    ]
