# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0007_auto_20170408_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='placeholder_ans',
            field=models.CharField(default='Answer', max_length=100),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='title',
            field=models.CharField(default='Level<django.db.models.fields.IntegerField>', max_length=100),
        ),
    ]
