# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0008_auto_20170409_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='level_no',
            field=models.IntegerField(),
        ),
    ]
