# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0010_auto_20170409_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='question_image',
            field=models.FileField(blank=True, null=True, upload_to='hunt/images/'),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
