# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0012_auto_20170409_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelmodel',
            name='question_image',
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='placeholder_ans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
