# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0013_auto_20170409_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='question_text',
            field=models.TextField(),
        ),
    ]
