# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0015_auto_20170409_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmodel',
            name='question_image',
            field=models.FileField(default='hunt/images.correct.jpg', upload_to='static/hunt/images/'),
        ),
    ]
