# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0017_auto_20170415_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='question_image',
            field=models.ImageField(default='hunt/images.correct.jpg', upload_to='static/hunt/images'),
        ),
    ]
