# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0019_auto_20170415_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='question_image',
            field=models.ImageField(upload_to='levels/'),
        ),
    ]
