# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0020_auto_20170415_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='question_image',
            field=models.FileField(upload_to='levels/'),
        ),
    ]
