# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0021_auto_20170701_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='question_image',
            field=models.ImageField(upload_to='levels/'),
        ),
    ]
